"""Initial Migration

Revision ID: 8ef1e38dbc0e
Revises: 
Create Date: 2026-09-18 15:25:21.485166
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8ef1e38dbc0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident',
    sa.Column('receipt_token_hash', sa.String(length=128), nullable=False),
    sa.Column('incident_type', sa.Enum('POLICE_BRUTALITY', 'CORRUPTION', 'GBV', 'GANG_ACTIVITY', 'UNREST', 'ROBBERY', 'ELECTORAL', 'OTHER', name='incidenttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'ROUTED', 'RESOLVED', name='incidentstatus'), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_city'), 'incident', ['city'], unique=False)
    op.create_index(op.f('ix_incident_created_at'), 'incident', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_id'), 'incident', ['id'], unique=True)
    op.create_index(op.f('ix_incident_incident_type'), 'incident', ['incident_type'], unique=False)
    op.create_index(op.f('ix_incident_receipt_token_hash'), 'incident', ['receipt_token_hash'], unique=False)
    op.create_index(op.f('ix_incident_region'), 'incident', ['region'], unique=False)
    op.create_index(op.f('ix_incident_status'), 'incident', ['status'], unique=False)
    op.create_table('routeassessment',
    sa.Column('origin_geohash', sa.String(length=12), nullable=False),
    sa.Column('dest_geohash', sa.String(length=12), nullable=False),
    sa.Column('route_geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('advisory_text', sa.Text(), nullable=False),
    sa.Column('incidents_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routeassessment_created_at'), 'routeassessment', ['created_at'], unique=False)
    op.create_index(op.f('ix_routeassessment_dest_geohash'), 'routeassessment', ['dest_geohash'], unique=False)
    op.create_index(op.f('ix_routeassessment_id'), 'routeassessment', ['id'], unique=True)
    op.create_index(op.f('ix_routeassessment_origin_geohash'), 'routeassessment', ['origin_geohash'], unique=False)
    op.create_table('safetyresource',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.Enum('SHELTER', 'LEGAL_AID', 'HOTLINE', 'HOSPITAL', 'CSO', 'POLICE_OVERSIGHT', name='resourcetype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('operating_hours', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safetyresource_created_at'), 'safetyresource', ['created_at'], unique=False)
    op.create_index(op.f('ix_safetyresource_id'), 'safetyresource', ['id'], unique=True)
    op.create_index(op.f('ix_safetyresource_region'), 'safetyresource', ['region'], unique=False)
    op.create_index(op.f('ix_safetyresource_resource_type'), 'safetyresource', ['resource_type'], unique=False)
    op.create_table('webintelligencecache',
    sa.Column('geohash', sa.String(length=12), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('content_summary', sa.Text(), nullable=False),
    sa.Column('threat_level', sa.Float(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webintelligencecache_created_at'), 'webintelligencecache', ['created_at'], unique=False)
    op.create_index(op.f('ix_webintelligencecache_geohash'), 'webintelligencecache', ['geohash'], unique=False)
    op.create_index(op.f('ix_webintelligencecache_id'), 'webintelligencecache', ['id'], unique=True)
    op.create_table('feedback',
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('helpful', sa.Boolean(), nullable=False),
    sa.Column('context', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['routeassessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_assessment_id'), 'feedback', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_assessment_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_webintelligencecache_id'), table_name='webintelligencecache')
    op.drop_index(op.f('ix_webintelligencecache_geohash'), table_name='webintelligencecache')
    op.drop_index(op.f('ix_webintelligencecache_created_at'), table_name='webintelligencecache')
    op.drop_table('webintelligencecache')
    op.drop_index(op.f('ix_safetyresource_resource_type'), table_name='safetyresource')
    op.drop_index(op.f('ix_safetyresource_region'), table_name='safetyresource')
    op.drop_index(op.f('ix_safetyresource_id'), table_name='safetyresource')
    op.drop_index(op.f('ix_safetyresource_created_at'), table_name='safetyresource')
    op.drop_table('safetyresource')
    op.drop_index(op.f('ix_routeassessment_origin_geohash'), table_name='routeassessment')
    op.drop_index(op.f('ix_routeassessment_id'), table_name='routeassessment')
    op.drop_index(op.f('ix_routeassessment_dest_geohash'), table_name='routeassessment')
    op.drop_index(op.f('ix_routeassessment_created_at'), table_name='routeassessment')
    op.drop_table('routeassessment')
    op.drop_index(op.f('ix_incident_status'), table_name='incident')
    op.drop_index(op.f('ix_incident_region'), table_name='incident')
    op.drop_index(op.f('ix_incident_receipt_token_hash'), table_name='incident')
    op.drop_index(op.f('ix_incident_incident_type'), table_name='incident')
    op.drop_index(op.f('ix_incident_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_created_at'), table_name='incident')
    op.drop_index(op.f('ix_incident_city'), table_name='incident')
    op.drop_table('incident')
    # ### end Alembic commands ###
