[supervisord]
logfile=/home/ubuntu/supervisord.log
user=ubuntu
nodaemon=true
log=DEBUG

[inet_http_server]
port=*:9051
username=safeground
password=super_safeground

[program:gunicorn]
command=/home/ubuntu/safeground/backend/venv/bin/gunicorn --log-config /home/ubuntu/safeground/backend/.deploy-services/logging.conf -k uvicorn.workers.UvicornWorker -w 4 --timeout 4000 --bind 0.0.0.0:8000 main:app
directory=/home/ubuntu/safeground/backend
user=ubuntu
stdout_logfile=/home/ubuntu/var/log/gunicorn/output.log
stderr_logfile=/home/ubuntu/var/log/gunicorn/error.log
autostart=true
autorestart=true
environment=PYTHONUNBUFFERED=1